# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
    - 0.3
    - 0.4
    - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("ThirdWay"); Pkg.test("ThirdWay"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("ThirdWay")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  